### ISSUE TITLE
Truck Kinematic Model

### ISSUE THREAD

**Issue by SiChiTong** [AtsushiSakai/HybridAStarTrailer#1]
Hi, Sir Sakai

It is really exciting and exiting for such ideas comes real!

May I know more about the model you have implemented ?

Many thanks!

**Comment by AtsushiSakai** [comment]
Hi @SiChiTong . Thank you for your interest.
I will add code and some description about it.
Please give me some time for me.

**Comment by SiChiTong** [comment]
Thanks for your kind response!

**Comment by SiChiTong** [comment]
Sir Sakai

Thanks for your update for providing the kinematic model that you are using.
Please have my appreciation for your quick response and I would close the issue as fulfillment.

Many thanks !

**Comment by AtsushiSakai** [comment]
@SiChiTong Welcome😃. I am going to upload the codes and finish writing README in this month.
