### ISSUE TITLE
add curvature continuous RS path planner and hybrid a*

### ISSUE THREAD

**Issue by AtsushiSakai** [AtsushiSakai/HybridAStarTrailer#11]

**Comment by gongxue46** [comment]
请问为什么A*算法最后一段路径是用RS计算的呢，为什么跳出循环的条件是是否有rs路径？

**Comment by AtsushiSakai** [comment]
@gongxue46 Sorry. I cannot read chinese...

**Comment by gongxue46** [comment]
Haha, sorry, I mean why only the last segment of the A* algorithm is calculated using RS. Why is the condition of jumping out of the loop whether there is an rs path?Thanks~

**Comment by AtsushiSakai** [comment]
@gongxue46 Please check the paper: https://ai.stanford.edu/~ddolgov/papers/dolgov_gpp_stair08.pdf
