### ISSUE TITLE
Some questions about rs_path

### ISSUE THREAD

**Issue by Scarabrine** [AtsushiSakai/HybridAStarTrailer#12]
Hi, Atsushi,

Your work is pretty impressive and I'm trying to reimplement your wok for interest. However, I get a question about the Reed-Shepp algorithm you use. Apparently, you first try to find a direct path by Reed-Shepp, if this path is feasible, you gonna directly use this one as the final path. But the problem is that I cannot find any information about gyaw1 in your code which makes me a little bit confused. So without the information about gyaw1, how do you ensure the final trailer orientation?

Best,

Jan

**Comment by AtsushiSakai** [comment]
@Scarabrine Hi. Thank you for your question.
> how do you ensure the final trailer orientation?
RS path can generate only a path for traditional vehicle, not for trailer.
I think it is impossible to ensure the trailer orientation with RS path.
So, in this system, I ignore the trailer orientation, just check the collision for the trailer rectancle.

**Comment by Scarabrine** [comment]
Hi, @AtsushiSakai , Thank you for your quick response. I also find out it's hard to add gyaw1 term in RS planner. I get your idea, I see you have done a step in 
`if abs(rs_path.pi_2_pi(yaw1[end] - gyaw1)) >= GOAL_TYAW_TH
            return false, nothing #no update
  end`
in trailer_hybrid_a_star.jl. I think you just pick one path that meets gyaw1 in all the candidates planned by RS planner. This totally makes sense. Maybe we can figure out a method to do that in RS planner to increase the speed but I think it's not the top priority thing right now. 

Thank for your quick response and detailed explanation.

**Comment by AtsushiSakai** [comment]
@Scarabrine 
>Maybe we can figure out a method to do that

If you have a good idea, your PR is welcome!!
