### ISSUE TITLE
a little slow?

### ISSUE THREAD

**Issue by hexiangquan** [AtsushiSakai/HybridAStarTrailer#4]
run time is longer than paper's reference time ?   Typical
running times for a full replanning cycle involving the hy-
brid A* search, CG smoothing, and interpolation were on
the order of 50–300ms

**Comment by AtsushiSakai** [comment]
@hexiangquan Trailer planning is mush more complicated than the paper's application. I think that is one reason of it.

**Comment by hexiangquan** [comment]
i donot think so , i have change code ,change tailer to car .still slow

**Comment by hexiangquan** [comment]
check_collision cause problem
